#! /bin/sh

# Truncate a couple of common commands that are used herein.
_bc() {
	bspc config "$@"
}

_check() {
	command -v "$1" > /dev/null
}


pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x nm-applet > /dev/null || nm-applet &
pgrep -x pasystray > /dev/null || pasystray &
pgrep -x blueman-applet > /dev/null || blueman-applet &
pgrep -x flameshot > /dev/null || flameshot &
pgrep -x dunst > /dev/null || dunst --config ~/.config/dunst/dunstrc &
pgrep -x picom > /dev/null || picom --experimental-backends --backend glx --config ~/dotfiles/picom/picom.conf &

feh --bg-fill ~/dotfiles/bgnd/real-wood.jpg
$HOME/dotfiles/polybar/launch_new.sh --new

WS1=Term
WS2=Web
WS3=Workspace
WS4=Study
WS5=Multimedia
WS0=Config

# bspc monitor -d $WS1 $WS2 $WS3 $WS4 $WS5 6 7 8 9 $WS0
if [ "$(bspc query -M | wc -l)" -eq 2 ]; then
	bspc monitor %DP-0 -d 1 2 3 4 5
	bspc monitor %HDMI-1 -d 6 7 8 9 0
else
	bspc monitor %DP-2 -d 1 2 3 4 5 6 7 8 9 0
fi

# Window Management
_bc border_width         2
_bc window_gap           2
_bc split_ratio          0.60
_bc borderless_monocle   false # Border required when we are in monocle in both moniters
_bc gapless_monocle      true
_bc single_monocle       true # Use monocle if only one window is present
_bc pointer_action1 move
_bc pointer_action2 resize_side


# We are giving instance name  ClassName:[InstanceName]:[Name]
# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
screenwidth=1920
screenheight=1200
windowwidth=800
windowheight=600
windowx=$(python -c "print(int($screenwidth)//2-int($windowwidth)//2)")
windowy=$(python -c "print(int($screenheight)//2-int($windowheight)//2)")

bspc rule -a persepolis state=floating follow=on rectangle="$windowwidth"x"$windowheight"+"$windowx"+"$windowy"
bspc rule -a mpv state=floating sticky=on follow=off focus=on rectangle="$windowwidth"x"$windowheight"+"$windowx"+"$windowy"
bspc rule -a "*:Toolkit:Picture-in-Picture" state=floating sticky=on follow=off focus=on rectangle="$windowwidth"x"$windowheight"+"$windowx"+"$windowy"
bspc rule -a Alacritty desktop='1'
bspc rule -a Google-chrome desktop='2'
bspc rule -a Vsim desktop='3'
bspc rule -a Vivado desktop='3'
bspc rule -a Evince desktop='6'
bspc rule -a "VirtualBox Machine"  state=floating follow=on rectangle="$windowwidth"x"$windowheight"+"$windowx"+"$windowy"
bspc rule -a Org.gnome.Nautilus state=floating follow=on rectangle="$windowwidth"x"$windowheight"+"$windowx"+"$windowy"
bspc rule -a vlc desktop='6'
bspc rule -a Arandr desktop='0'
bspc rule -a Blueman-manager desktop='0'
bspc rule -a processing-app-Base state=pseudo_tiled

bspc rule -a CMakeSetup state=floating

# Set urgent for new windows
bspc subscribe node_add | while read -a msg; do
    bspc query -D -d "${msg[2]}.!focused" > /dev/null \
        && xdotool set_window --urgency 1 "${msg[4]}"
done


# Required for java applications to work
wmname LG3D
export _JAVA_AWT_WM_NONREPARENTING=1
export EDITOR=nvim
